# Generated by Django 4.0.2 on 2022-04-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produtoconsumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoConsumo',
        ),
    ]
